package com.shiftorganization.shared.db

import org.jetbrains.exposed.sql.Table
import org.jetbrains.exposed.sql.javatime.timestampWithTimeZone

/**
 * Exposed table definition for the `properties` relation.
 *
 * Mirrors the DDL in `V1__create_tables.sql`:
 * ```sql
 * CREATE TABLE properties (
 *     id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *     owner_id    TEXT          NOT NULL,
 *     address     TEXT          NOT NULL,
 *     description TEXT,
 *     price_night NUMERIC(10,2) NOT NULL,
 *     status      TEXT          NOT NULL DEFAULT 'available',
 *     created_at  TIMESTAMPTZ   NOT NULL DEFAULT now(),
 *     updated_at  TIMESTAMPTZ   NOT NULL DEFAULT now()
 * );
 * ```
 *
 * Valid `status` values: `available` | `unavailable` | `deleted`.
 */
object PropertiesTable : Table("properties") {

    /** UUID primary key — generated by the repository or PostgreSQL default. */
    val id = uuid("id")

    /** Cognito `sub` of the property owner. */
    val ownerId = text("owner_id")

    /** Physical address used for full-text search in OpenSearch. */
    val address = text("address")

    /** Optional long-form description. */
    val description = text("description").nullable()

    /** Nightly rental price; stored as `NUMERIC(10,2)` in the database. */
    val priceNight = decimal("price_night", precision = 10, scale = 2)

    /**
     * Lifecycle status of the property.
     * Allowed values: `available`, `unavailable`, `deleted`.
     */
    val status = text("status").default("available")

    /** Row creation timestamp (managed by the database). */
    val createdAt = timestampWithTimeZone("created_at")

    /** Row last-updated timestamp (managed by the database). */
    val updatedAt = timestampWithTimeZone("updated_at")

    override val primaryKey = PrimaryKey(id)
}
